import Head from 'next/head'
import { initializeApp } from 'firebase/app'
import { getFirestore, collection, query, doc, getDocs } from "firebase/firestore";
import AddrItem from '../components/AddrItem'
import AddrList from '../components/AddrList'
import Chart from '../components/Chart'
import styles from '/styles/pages/index.module.css'
const app = initializeApp(process.env.firebaseConfig)
const db = getFirestore(app)

export default (props) => {
  return (
    <>
      <Head>
        <title>WhaleWatcher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main  className={styles.container}>
        <Chart />
        <AddrList data={props.data} />
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const bitcoinRef = collection(db, 'bitcoin_address')
  const snapshot = await getDocs(bitcoinRef)
  const data = snapshot.docs.map(d => d.data())
  return { props: { data } }
}

